import = [
    "/themes/themes/coolnight.toml"
] 

[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14

[keyboard]
bindings = [
  { key = "Escape", mods = "Control",                            action = "ToggleViMode"   },
  { key = "(",      mods = "alt",                                chars = '{'               },
  { key = ")",      mods = "alt",                                chars = '}'               },
  { key = "(",      mods = "alt|shift",                          chars = '['               },
  { key = ")",      mods = "alt|shift",                          chars = ']'               },
  { key = "l",      mods = "alt|shift",                          chars = '|'               },
  { key = ":",      mods = "alt|shift",                          chars = '\'               },
  { key = "$",      mods = "alt",                                chars = '€'               },
  { key = "n",      mods = "alt",                                chars = '~'               },
]
